config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # /users
  # /users/:id
  # /users/:id/posts/:id
  
  resources :users, only: [:index, :show, :new, :create] do
    resources :posts, only: [:show, :new, :create]
  end
  
  root "users#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def show
    @post = Post.find(params[:id])
  end
  
  def new
    @user = User.find(params[:user_id])
    @post = Post.new
  end
  
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    
    if @post.save
      redirect_to @user
    end
    
  end
  
  private
  def post_params
    params.require(:post).permit(:title,:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to @user
    else
      @errors = @user.errors.full_messages
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :age, :city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spacebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for [@user,@post] do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.submit "Create Post" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<p>&mdash; <%= @post.user.username %></p>

app/views/users/index.html.erb
<h1>Users</h1>
<p><%= link_to "New User", new_user_path %>
<ul>
<% @users.each do |user| %>
  <li><%= link_to user.username, user, class: 'this-is-a-class' %></li>
<% end %>
</ul>

app/views/users/new.html.erb
<h1>New User Form</h1>
<% if @errors %>
<ul>
  <% @errors.each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>
<%= form_for @user, html: {class: "form-class"} do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "Enter Username", class: 'this-is-a-class' %>
  </div>
  
  <div>
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  
  <div>
    <%= f.label :city %>
    <%= f.text_field :city, placeholder: "Enter City" %>
  </div>
  
  <div>
    <%= f.submit "Create User" %>
  </div>
  
  
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<p><strong>Age</strong> <%= @user.age %></p>
<p><strong>City</strong> <%= @user.city %></p>

<%= link_to "New Post", new_user_post_path(@user) %>

<h2>Posts</h2>
<ul>
  <% @user.posts.each do |post| %>
  <li><%= link_to post.title, user_post_path(@user,post) %></li>
  <% end %>
</ul>